name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"


environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  meta:
  json_annotation:

dev_dependencies:
  lints: ^6.0.0
  glob:
  lean_builder:
    path: ..



